Add option to specify maximum guild count per shard or process
nyxx-discord/nyxx_sharding pull request #14
Opened 2022-02-11 14:49 UTC by abitofevrything

# Description

Adds new options for calculating shard and process counts.

## Connected issues & other potential problems

Closes #11 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] Ran `dart analyze` or `make analyze` and fixed all issues
- [x] Ran `dart format --set-exit-if-changed -l 160 ./lib` or `make format` and fixed all issues
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my changes haven't lowered code coverage

2022-02-16 23:25 UTC, l7ssha requested changes

2022-02-16 23:25 UTC, l7ssha commented on lib/src/sharding_manager.dart
> +  }
this whole thing needs to be taken apart into smaller functions maybe because its unclear whats its doing

2022-02-16 23:25 UTC, l7ssha commented on lib/src/sharding_manager.dart
> +      if (data.length < 200) {
why 200 and whats the purpose of while loop?

2022-02-17 06:11 UTC, abitofevrything commented on lib/src/sharding_manager.dart
> +      if (data.length < 200) {
This endpoint is paged and has a maximum of 200 guilds per request - if there are less than 200 guilds in the response then we know that we are done getting all the guilds. Until that condition is hit, we keep on looping, requesting the next 200 guilds.

2022-02-18 09:58 UTC, l7ssha submitted a review, later dismissed

2022-02-18 17:41 UTC, l7ssha approved these changes

2022-02-18 17:48 UTC, merged