Implement process communication
nyxx-discord/nyxx_sharding pull request #15
Opened 2022-02-13 14:52 UTC by abitofevrything

# Description

Adds a way for spawned processes to communicate with the manager process and vice versa. Also adds utility methods for fetching various statistics about other processes.

## Connected issues & other potential problems

Closes #12 

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] Ran `dart analyze` or `make analyze` and fixed all issues
- [x] Ran `dart format --set-exit-if-changed -l 160 ./lib` or `make format` and fixed all issues
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my changes haven't lowered code coverage

2022-02-16 23:23 UTC, l7ssha requested changes

2022-02-17 06:05 UTC, abitofevrything commented on lib/src/communication/sharding_plugin.dart
> +  late int seqNum = Random().nextInt(1000);
Chosen arbitrarily really, the goal is to avoid that any two processes end up with the same sequence number to avoid requests being confused.

2022-02-17 06:05 UTC, abitofevrything commented on lib/src/communication/sharding_plugin.dart
> +  final Completer<void> connectedCompleter = Completer();
Since the class itself isn't exported (only the interface), then the fields don't need to be private.

2022-02-17 06:07 UTC, abitofevrything commented on lib/src/communication/common.dart
> +  Future<List<int>> getCachedChannels();
If it were a stream the manager process wouldn't know when to close it and it would also mean more requests overall as the manager process needs to seen an update for each data update instead of only one once all the data is received.

2022-02-18 09:58 UTC, l7ssha submitted a review, later dismissed

2022-02-18 17:41 UTC, l7ssha approved these changes

2022-02-18 17:43 UTC, merged